# AWS Region
 aws_region: us-west-2

# VPC Information
 vpc_name: pro_vpc
 vpc_cidr_block: 172.31.10.0/24

# For Security Group Rule
 my_ip_range: 172.31.10.0 - 172.31.10.12

# Subnets
 public_subnet_1_cidr: 172.31.10.0/27
